version: '3.8'

services:
  ambev.developerevaluation.webapi:
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - ambev.developerevaluation.database

  ambev.developerevaluation.database:
    ports:
      - "49916:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
